"""empty message

Revision ID: 48a4afd62055
Revises: 45148a62f3e9
Create Date: 2024-03-13 13:34:29.450325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a4afd62055'
down_revision = '45148a62f3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('single', sa.Boolean(), nullable=True),
    sa.Column('audio', sa.String(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album_table.id'], name=op.f('fk_track_table_album_id_album_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_table')
    # ### end Alembic commands ###
