"""empty message

Revision ID: 699db1e5aa2d
Revises: 48a4afd62055
Create Date: 2024-03-13 13:39:33.899200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699db1e5aa2d'
down_revision = '48a4afd62055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_table', sa.Column('album', sa.String(), nullable=True))
    op.add_column('album_table', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('album_table', sa.Column('label', sa.String(), nullable=True))
    op.add_column('album_table', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album_table', 'image')
    op.drop_column('album_table', 'label')
    op.drop_column('album_table', 'genre')
    op.drop_column('album_table', 'album')
    # ### end Alembic commands ###
